version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels: ["dependencies"]
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    allow:
      - dependency-type: "all"
    # reviewers:
    #   - your-github-handle
    # assignees:
    #   - your-github-handle

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "deps"
    labels: ["dependencies"]
